### ISSUE TITLE
resources to learn PCL CUDA programming  

### ISSUE THREAD

**Issue by srinivasrama** [lacie-life/Jellyfish-with-Robotics#1]
Please share resources to learn PCL CUDA programming  if possible 
[https://github.com/lacie-life/Jellyfish-with-Robotics/tree/master/Course/CUDA-in-Robotic](https://github.com/lacie-life/Jellyfish-with-Robotics/tree/master/Course/CUDA-in-Robotic)

**Comment by lacie-life** [comment]
This is the origin [repo of course](https://github.com/JanuszBedkowski/gpu_computing_in_robotics), i only follow this repo
